matrix:
    include:
        - language: csharp
          dist: xenial
          mono: none
          dotnet: 2.2
          solution: Algodore.sln
          env:
              - DOTNET_CONFIGURATION=Debug
              - DOTNET_CONFIGURATION=Release
          script:
              - dotnet restore
              - dotnet test -c $DOTNET_CONFIGURATION
