matrix:
    include:
        - language: csharp
          mono: none
          dotnet: 2.1.502
          solution: Algodore.sln
          script:
              - dotnet restore
              - dotnet test
