matrix:
    include:
        - language: csharp
          dist: xenial
          mono: none
          dotnet: 2.2
          solution: Algodore.sln
          script:
              - dotnet restore
              - dotnet build
              - dotnet test
